server:
  port: 8089

spring:
  http:
    multipart:
      enabled: true
      max-file-size: 10MB #文件大小
      max-request-size: 10MB #请求大小
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false #缓存

########################################################
# 自定义的配置
########################################################
custom:
  fileUploadPath: D:/test/ #文件存储目录
